trigger CustomerDetailsTrigger on Customer_Details__c (Before Insert, Before Update, Before Delete, After Update) {
    if(Trigger.isBefore && Trigger.isInsert){
        for(Customer_Details__c cd : Trigger.New){
            if(cd.Phone_Number__c.length() < 10){
                cd.Phone_Number__c.addError('Phone Number Must be of 10 Digits');
            }
            if(cd.Total_Veg_Bill__c != Null){
                cd.Total_Veg_Bill__c.addError('This Field will be Autogenerated...Don not Enter any Value here');
            }
            if(cd.Total_Non_Veg_Bill__c != Null){
                cd.Total_Non_Veg_Bill__c.addError('This Field will be Autogenerated...Don not Enter any Value here');
            }
            if(cd.Total_Bill__c != Null){
                cd.Total_Bill__c.addError('This Field will be Autogenerated...Don not Enter any Value here');
            }
            if(cd.Total_Veg_Bill__c == Null && cd.Total_Non_Veg_Bill__c == Null && cd.Total_Bill__c == Null){
                cd.Total_Veg_Bill__c = 0;
                cd.Total_Non_Veg_Bill__c = 0;
                cd.Total_Bill__c = 0;
            }
        }
    }
    if(Trigger.isBefore && Trigger.isUpdate){
        for(Customer_Details__c cd : Trigger.New){
            cd.Total_Bill__c = cd.Total_Veg_Bill__c + cd.Total_Non_Veg_Bill__c;
        }
    }
    /*if(Trigger.isAfter && Trigger.isUpdate){
        List<Messaging.SingleEmailMessage> emailObs = new List<Messaging.SingleEmailMessage>();
        for(Customer_Details__c cd : Trigger.New){
            if(cd.Total_Bill__c > 0){
                Messaging.SingleEmailMessage msgobs = new Messaging.SingleEmailMessage();
                msgobs.setToAddresses(new String[] {'aniketkumar.singh.1997@gmail.com'});
                msgobs.setSubject('You have registered with Us');
                msgobs.setPlainTextBody('Hello Welcome to Babumosshhaai!!!!.... Your Total Bill is ' + cd.Total_Bill__c);
                emailObs.add(msgobs);
            }  
        }
        Messaging.sendEmail(emailObs);
    }*/
    if(Trigger.isBefore && Trigger.isDelete){
        for(Customer_Details__c cd : Trigger.Old){
            cd.addError('Deletion of Record is not Allowed.....');
        }
    }
}