trigger NonVegTrigger on Non_Veg_Main_Course__c (Before Insert, Before Update, After Insert) {
    if(Trigger.isBefore && Trigger.isInsert){
        for(Non_Veg_Main_Course__c nvg : Trigger.New){
            if(nvg.Total_Non_Veg_Bill__c != Null){
                nvg.Total_Non_Veg_Bill__c.addError('You Cannot Enter any Value in this field..This Field Value will be Autogenerated.!!');
            }
        }
    }
    if(Trigger.isBefore && Trigger.isInsert || Trigger.isUpdate){
        NonVegTriggerHelper.nonVegBeforeInsertUpdateHandlerOne(Trigger.New);
        NonVegTriggerHelper.nonVegBeforeInsertUpdateHandlerTwo(Trigger.New);
        NonVegTriggerHelper.itemsOrdered(Trigger.New);
    }
    If(Trigger.isAfter && Trigger.isInsert){
        Set<Id> ids = new Set<Id>();
        for(Non_Veg_Main_Course__c nvmc : Trigger.New){
            ids.add(nvmc.Customer_Name__c);
        }
        List<Customer_Details__c> cdList = [SELECT Id, Name, Total_Non_Veg_Bill__c, 
                                            (SELECT Id, Total_Non_Veg_Bill__c 
                                            FROM Non_Veg_Main_Course__r) 
                                            FROM Customer_Details__c WHERE Id IN : ids];
        for(Customer_Details__c cd : cdList){
            Decimal x=0;
            for(Non_Veg_Main_Course__c v : cd.Non_Veg_Main_Course__r){
                if(v.Total_Non_Veg_Bill__c != Null){
                    x = x + v.Total_Non_Veg_Bill__c;
                }
            }
            cd.Total_Non_Veg_Bill__c = x;
        }
        update cdList;
    }
}