trigger VegTrigger on Veg_Main_Course__c (Before Insert, Before Update, After Insert) {
    if(Trigger.isBefore && Trigger.isInsert){
        for(Veg_Main_Course__c vg : Trigger.New){
            if(vg.Total_Veg_Bill__c != Null){
                vg.Total_Veg_Bill__c.addError('You Cannot Enter any Value in this field..This Field Value will be Autogenerated.!!');
            }
        }
    }    
    if(Trigger.isBefore && Trigger.isInsert || Trigger.isUpdate){
        VegTriggerHelper.vegBeforeInsertUpdateHandlerOne(Trigger.New);
        VegTriggerHelper.vegBeforeInsertUpdateHandlerTwo(Trigger.New);
        VegTriggerHelper.itemsOrdered(Trigger.New);
    }
    If(Trigger.isAfter && Trigger.isInsert){
        Set<Id> ids = new Set<Id>();
        for(Veg_Main_Course__c vmc : Trigger.New){
            ids.add(vmc.Customer_Name__c);
        }
        List<Customer_Details__c> cdList = [SELECT Id, Name, Total_Veg_Bill__c, 
                                            (SELECT Id, Total_Veg_Bill__c 
                                            FROM Veg_Main_Courses__r) 
                                            FROM Customer_Details__c WHERE Id IN : ids];
        for(Customer_Details__c cd : cdList){
            Decimal x=0;
            for(Veg_Main_Course__c v : cd.Veg_Main_Courses__r){
                if(v.Total_Veg_Bill__c != Null){
                    x = x + v.Total_Veg_Bill__c;
                }
            }
            cd.Total_Veg_Bill__c = x;
        }
        update cdList;
    }
}